/-
Copyright (c) 2026 Dillon Ryan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dillon Ryan
-/
import Mathlib

/-!
# THE PERFECT-SQUARE LAW AS A CERTIFIED IDENTITY
(the "resultant is a norm" theorem, Dickson core).
The Salem tower rung L_k = |Res(P, x^(2^k)+1)| is a perfect square (verified on all 264
deg-10 resultants of the accompanying census). x^(2^k)+1 = Φ_{2^(k+1)} is cyclotomic, so L_k is a
field norm; the square is EXACT and structural: for a reciprocal (Salem) P with
trace polynomial P_tr (roots Y_i = α_i + α_i⁻¹),
  √L_k = |Res(P_tr, D_{2^(k−1)})|,     L_k = Res(P_tr, D_{2^(k−1)})²
(verified exactly in ℤ for lehmer/floor2/salem8, k=1..5), where D_n is the
Dickson polynomial of the first kind — the INTEGER-coefficient trace-coordinate
Chebyshev, D_n(α+α⁻¹) = αⁿ+α⁻ⁿ. This module certifies the structural heart:
· `dickson_two`   : D₂ = X² − 2 — the integer generator of the tower;
· `dickson_double`: D_{2n} = D_n² − 2 — the 2-adic rungs are its SQUARING
  iterates (the integer-polynomial version of the cosh-doubling); every rung
  is an integer-polynomial image of the trace atoms ⟹ the norm is an integer;
· `dickson_cosh`  : D_n(2·cosh u) = 2·cosh(n·u) — the rapidity bridge: the
  integer Dickson at the atom 2cosh(mass) yields 2cosh(n·mass);
· `dickson_trace_atom` : D_n(λ+λ⁻¹) = λⁿ+λ⁻ⁿ — the defining trace identity,
  the exact factor of √L_k.
Together: the tower is generated by iterating the integer polynomial X²−2, and
evaluating it at the Salem trace atom gives the rapidity ladder — integrality
(hence the perfect square) and the rapidity are ONE identity.
-/

namespace SalemTower

open Polynomial

/-- **The integer generator.** `D₂ = X² − 2` (Dickson first kind, parameter 1):
the doubling map of the 2-adic tower is a monic integer polynomial. -/
theorem dickson_two {R : Type*} [CommRing R] : dickson 1 (1 : R) 2 = X ^ 2 - 2 := by
  have h := dickson_add_two 1 (1 : R) 0
  simp only [zero_add, dickson_one, dickson_zero, Nat.cast_one, map_one, one_mul] at h
  rw [h]; ring

/-- **The 2-adic rungs are squaring iterates.** `D_{2n} = D_n² − 2`: the tower
map on trace atoms is `y ↦ y² − 2` (= D₂), an integer polynomial — the exact,
integer-coefficient version of the cosh-doubling `cosh(2v) = 2cosh²v − 1`. Every
rung is an integer-polynomial image of the trace atoms, so `Res(P_tr, D_{2^k})`
is a rational integer and `L_k` its square. -/
theorem dickson_double {R : Type*} [CommRing R] (n : ℕ) :
    dickson 1 (1 : R) (2 * n) = (dickson 1 (1 : R) n) ^ 2 - 2 := by
  rw [dickson_one_one_mul, dickson_two]
  simp only [sub_comp, pow_comp, X_comp, ofNat_comp]
  push_cast
  ring

/-- **The rapidity bridge.** `D_n(2·cosh u) = 2·cosh(n·u)`: the integer Dickson
polynomial evaluated at the atom `2cosh(mass)` produces `2cosh(n·mass)`. Binds
integrality (integer polynomial) to the rapidity (cosh of the scaled mass) in
one identity — the census mechanism upgraded to a certified relation. -/
theorem dickson_cosh (u : ℝ) :
    ∀ n : ℕ, (dickson 1 (1 : ℝ) n).eval (2 * Real.cosh u) = 2 * Real.cosh ((n : ℝ) * u)
  | 0 => by simp [dickson_zero, Real.cosh_zero]; norm_num
  | 1 => by simp [dickson_one]
  | (n + 2) => by
    have h1 := dickson_cosh u (n + 1)
    have h2 := dickson_cosh u n
    have key : 2 * Real.cosh (((n : ℝ) + 2) * u)
        = (2 * Real.cosh u) * (2 * Real.cosh (((n : ℝ) + 1) * u))
          - 2 * Real.cosh ((n : ℝ) * u) := by
      have hps : Real.cosh (((n : ℝ) + 1) * u + u)
          + Real.cosh (((n : ℝ) + 1) * u - u)
          = 2 * Real.cosh (((n : ℝ) + 1) * u) * Real.cosh u := by
        rw [Real.cosh_add, Real.cosh_sub]; ring
      have e1 : ((n : ℝ) + 1) * u + u = ((n : ℝ) + 2) * u := by ring
      have e2 : ((n : ℝ) + 1) * u - u = (n : ℝ) * u := by ring
      rw [e1, e2] at hps; nlinarith [hps]
    rw [dickson_add_two]
    simp only [eval_sub, eval_mul, eval_X, map_one, one_mul, h1, h2]
    push_cast
    linarith [key]

/-- **The defining trace identity.** `D_n(λ+λ⁻¹) = λⁿ + λ⁻ⁿ`: the integer Dickson
polynomial at the Salem trace atom λ+λ⁻¹ returns the power-sum — exactly the
factor `(λ^(2^(k−1)) + λ^(−2^(k−1)))` of `√L_k`. -/
theorem dickson_trace_atom {lam : ℝ} (h : 0 < lam) (n : ℕ) :
    (dickson 1 (1 : ℝ) n).eval (lam + lam⁻¹) = lam ^ n + (lam⁻¹) ^ n := by
  have e : lam + lam⁻¹ = 2 * Real.cosh (Real.log lam) := by
    rw [Real.cosh_eq, Real.exp_neg, Real.exp_log h]; ring
  rw [e, dickson_cosh, Real.cosh_eq, Real.exp_neg, Real.exp_nat_mul, Real.exp_log h,
      inv_pow]
  ring

end SalemTower
