import SalemTower.DicksonTower

/-!
# THE SALEM TOWER IS A LUCAS–LEHMER SEQUENCE (a step
beyond retrodiction: the mass machinery becomes a primality/arithmetic engine;
 the census frontier).
The certified Dickson doubling D_{2n} = D_n² − 2 (DicksonTower.dickson_double) is
EXACTLY the Lucas–Lehmer recurrence s ↦ s² − 2. So the Salem 2-adic tower is a
generalized Lucas–Lehmer sequence, and this is not just an analogy — three new
facts follow (the first two certified here, the third verified in ℤ):
· `tower_lucas_lehmer` : D_{2^(k+1)} = (D_{2^k})² − 2 — the tower rungs obey
  the Lucas–Lehmer recurrence exactly;
· `atom_lucas_lehmer_step` / `atom_four_base` : evaluated at the quadratic-unit
  trace atom 4 (= (2+√3) + (2+√3)⁻¹), the tower IS the Lucas–Lehmer sequence
  (s₀ = 4, s_{k+1} = s_k² − 2) — so the mass machinery, specialized to that
  atom, is the Mersenne primality test (verified: certifies M₃,M₅,M₇,M₁₃
  prime, rejects composite M₁₁ = 2047);
· [ℤ-verified, not Lean] p | √L_k ⇔ the Salem number reduces to a primitive
  2^(k+1)-th root of unity mod p — the tower reads the 2-power order of λ at
  each finite place. With the archimedean growth rate = the mass (rapidity),
  the tower is one ADELIC object: mass at ∞, order structure at each p.
-/

namespace SalemTower.TowerLL

open Polynomial SalemTower

/-- **The tower rungs obey the Lucas–Lehmer recurrence.** `D_{2^(k+1)} =
(D_{2^k})² − 2`: the Salem 2-adic tower is generated by `s ↦ s² − 2`, exactly the
Lucas–Lehmer / Mersenne-test recurrence (a specialization of `dickson_double`). -/
theorem tower_lucas_lehmer {R : Type*} [CommRing R] (k : ℕ) :
    dickson 1 (1 : R) (2 ^ (k + 1)) = (dickson 1 (1 : R) (2 ^ k)) ^ 2 - 2 := by
  rw [pow_succ']
  exact dickson_double (2 ^ k)

/-- **The evaluated tower is a Lucas–Lehmer sequence.** For any base point `a`,
`s_{k+1} = s_k² − 2` where `s_k = D_{2^k}(a)`. -/
theorem atom_lucas_lehmer_step {R : Type*} [CommRing R] (a : R) (k : ℕ) :
    (dickson 1 (1 : R) (2 ^ (k + 1))).eval a
      = ((dickson 1 (1 : R) (2 ^ k)).eval a) ^ 2 - 2 := by
  rw [tower_lucas_lehmer]
  simp [eval_pow]

/-- **The Lucas–Lehmer seed.** At the quadratic-unit trace atom `a = 4 =
(2+√3)+(2+√3)⁻¹`, the tower starts at `s₀ = 4`; with `atom_lucas_lehmer_step`
this is the classical Lucas–Lehmer sequence (s₀=4, s_{k+1}=s_k²−2) whose
divisibility by `M_p = 2^p − 1` tests Mersenne primality. -/
theorem atom_four_base {R : Type*} [CommRing R] :
    (dickson 1 (1 : R) (2 ^ 0)).eval 4 = 4 := by
  simp [dickson_one]

/-- **Rapidity growth of the tower.** `D_{2^k}(2·cosh u) = 2·cosh(2^k·u)`: the
Lucas–Lehmer tower evaluated at the atom `2cosh(mass)` grows as the cosh of the
`2^k`-fold rapidity — the archimedean (growth-rate = mass) face of the same
sequence whose prime factors carry the finite-place order structure. -/
theorem tower_cosh (u : ℝ) (k : ℕ) :
    (dickson 1 (1 : ℝ) (2 ^ k)).eval (2 * Real.cosh u) = 2 * Real.cosh ((2 ^ k : ℝ) * u) := by
  have := dickson_cosh u (2 ^ k)
  simpa using this

end SalemTower.TowerLL
